### ISSUE TITLE
Throwing Error for no autocomplete tags password/email for registration/login

### ISSUE THREAD

**Issue by ParkerM2** [johnkomarnicki/active_tracker#2]

**Comment by dave-lence** [comment]
i need your assistance, i am getting errors saying webpack compiled with 5 errors and so many compiled errors please how can i resolve this issue

**Comment by ParkerM2** [comment]
@dave-lence might want to open a new issue I haven't looked at this code since december.. Also I think a new version of supabase is out and that could likely cause issues so maybe look into that.
